name: Test Makefile for update git modules

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Makefile
      run: |
        if [ ! -f Makefile ]; then
          echo "Makefile not found"
          exit 1
        fi

    - name: Display help
      run: make help

    - name: Setup Git user
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Setup test environment
      run: |
        mkdir -p modules
        git submodule add https://github.com/octocat/Hello-World.git modules/test-module-1
        git submodule add https://github.com/octocat/Hello-World.git modules/test-module-2
        git submodule init
        git submodule update

    - name: Test update-all
      run: make update-all

    - name: Test init-update
      run: make init-update

    - name: Test with custom MODULES_DIR
      run: |
        mkdir -p custom_modules
        git submodule add https://github.com/octocat/Hello-World.git custom_modules/test-module-3
        make update-all MODULES_DIR=custom_modules
        make init-update MODULES_DIR=custom_modules
